In [1]:
# Bài 1 2.2 2.3 đọc không làm
import numpy as np
signals = np.array([
    [1, 2],
    [3, 4],
    [10, 0]
])

sample = np.array([3, -1])
result = np.inner(signals, sample)

print("Kết quả tích vô hướng là:", result)



Kết quả tích vô hướng là: [ 1  5 30]


In [2]:
# Bài 1.1
import numpy as np

A = np.array([0, 0, -1, 2, 3, -1, 0, 1, -1, -1])
search_vector = np.array([0, 1, -1])
print("Độ dài A:", len(A))
print("Độ dài search_vector:", len(search_vector))

num_rows = len(A) - len(search_vector) + 1
B = np.zeros((num_rows, len(search_vector)), dtype=int)
for i in range(num_rows):
    for j in range(len(search_vector)):
        B[i, j] = A[i + j]

print("Ma trận B chứa các đoạn con:")
print(B)
C = np.inner(B, search_vector)

print("Giá trị dot product của từng dòng với search_vector:")
print(C)

target = np.inner(search_vector, search_vector)
print("Dot product chuẩn (search_vector ⋅ search_vector):", target)
print("Các vị trí khớp:")
for i in range(num_rows):
    if C[i] == target:
        print(f"Vị trí {i}:", B[i])


Độ dài A: 10
Độ dài search_vector: 3
Ma trận B chứa các đoạn con:
[[ 0  0 -1]
 [ 0 -1  2]
 [-1  2  3]
 [ 2  3 -1]
 [ 3 -1  0]
 [-1  0  1]
 [ 0  1 -1]
 [ 1 -1 -1]]
Giá trị dot product của từng dòng với search_vector:
[ 1 -3 -1  4 -1 -1  2  0]
Dot product chuẩn (search_vector ⋅ search_vector): 2
Các vị trí khớp:
Vị trí 6: [ 0  1 -1]


In [3]:
# Bài 2.1
import numpy as np

A = np.array([
    [0, 1, 1, 1],
    [1, 0, 1, 1],
    [1, 1, 0, 1],
    [1, 1, 1, 0]
])
x = np.array([1.0, 1.0, 1.0, 1.0])
x = np.dot(A, x)
print("Kết quả lần nhân đầu tiên:")
print(x)
print("\nLặp lại phép nhân 10 lần và in kết quả mỗi lần:")
for i in range(10):
    x = np.dot(A, x)
    print(f"Lần {i+1}:", x)


Kết quả lần nhân đầu tiên:
[3. 3. 3. 3.]

Lặp lại phép nhân 10 lần và in kết quả mỗi lần:
Lần 1: [9. 9. 9. 9.]
Lần 2: [27. 27. 27. 27.]
Lần 3: [81. 81. 81. 81.]
Lần 4: [243. 243. 243. 243.]
Lần 5: [729. 729. 729. 729.]
Lần 6: [2187. 2187. 2187. 2187.]
Lần 7: [6561. 6561. 6561. 6561.]
Lần 8: [19683. 19683. 19683. 19683.]
Lần 9: [59049. 59049. 59049. 59049.]
Lần 10: [177147. 177147. 177147. 177147.]


In [4]:
# Bài Tập 3
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

def resize_image(image_array, new_width, new_height):
    """
    Resize ảnh bằng cách nội suy gần nhất (nearest-neighbor).
    image_array: ảnh numpy (H, W, C) hoặc (H, W)
    Trả về: ảnh đã resize kích thước (new_height, new_width, C)
    """
    old_height, old_width = image_array.shape[:2]

    if image_array.ndim == 3:
        new_image = np.zeros((new_height, new_width, image_array.shape[2]), dtype=np.uint8)
    else:
        new_image = np.zeros((new_height, new_width), dtype=np.uint8)
    scale_y = old_height / new_height
    scale_x = old_width / new_width

    for y in range(new_height):
        for x in range(new_width):

            src_y = int(y * scale_y)
            src_x = int(x * scale_x)

            new_image[y, x] = image_array[src_y, src_x]

    return new_image

img = Image.open("your_image.jpg")
img = img.convert("RGB")
img_np = np.array(img)
resized_img = resize_image(img_np, new_width=100, new_height=100)
plt.subplot(1, 2, 1)
plt.title("Ảnh gốc")
plt.imshow(img_np)
plt.axis('off')

plt.subplot(1, 2, 2)
plt.title("Ảnh đã resize")
plt.imshow(resized_img)
plt.axis('off')

plt.show()


FileNotFoundError: [Errno 2] No such file or directory: 'your_image.jpg'

Bài Tập Về Nhà


In [5]:
# Bài 2
# Kernel a (kiểu Laplacian 4 hướng)
kernel_a = np.array([
    [ 0, -1,  0],
    [-1,  4, -1],
    [ 0, -1,  0]
])

kernel_b = np.array([
    [-1, -1, -1],
    [-1,  8, -1],
    [-1, -1, -1]
])
def edge_emphasis(image_array, kernel):
    return convolve2d(image_array, kernel, mode='same', boundary='symm')
img = Image.open("your_image.jpg").convert("L")
img_array = np.array(img)
edge_a = edge_emphasis(img_array, kernel_a)
edge_b = edge_emphasis(img_array, kernel_b)
plt.figure(figsize=(10, 4))

plt.subplot(1, 3, 1)
plt.title("Ảnh gốc")
plt.imshow(img_array, cmap='gray')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.title("Rút xương – Kernel A")
plt.imshow(edge_a, cmap='gray')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.title("Rút xương – Kernel B")
plt.imshow(edge_b, cmap='gray')
plt.axis('off')

plt.tight_layout()
plt.show()


FileNotFoundError: [Errno 2] No such file or directory: 'your_image.jpg'

In [6]:
# Bài 1
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from scipy.signal import convolve2d
gaussian_kernel = np.array([
    [1,  4,  7,  4, 1],
    [4, 16, 26, 16, 4],
    [7, 26, 41, 26, 7],
    [4, 16, 26, 16, 4],
    [1,  4,  7,  4, 1]
], dtype=np.float32)

gaussian_kernel /= np.sum(gaussian_kernel)
def apply_gaussian_blur(image_array):
    return convolve2d(image_array, gaussian_kernel, mode='same', boundary='symm')
img = Image.open("your_image.jpg").convert("L")
img_array = np.array(img)
blurred_img = apply_gaussian_blur(img_array)
plt.subplot(1, 2, 1)
plt.title("Ảnh gốc")
plt.imshow(img_array, cmap='gray')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.title("Làm mờ Gaussian")
plt.imshow(blurred_img, cmap='gray')
plt.axis('off')

plt.show()


FileNotFoundError: [Errno 2] No such file or directory: 'your_image.jpg'