In [ ]:
# Bài 1
import numpy as np
n = 4
X = np.array(range(1,n+1))
sigma = np.array([4,3,2,1])
def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(X)-1):
            for j in range (i+1,len(X)):
                    ket_qua = ket_qua * ((X[i]-X[j])/(sigma[i]-sigma[j]))
    return int(ket_qua)
sigma =np.array([2,1,3,4])
sgn_by_def(sigma)

-1

In [ ]:
from itertools import permutations
import numpy as np
n = 3
X = [i for i in range(1, n + 1)]
Sn = list(permutations(X))
print("Tập hoán vị Sn:")
print(Sn)
det = 0
def sgn(permutation):
    count = 0
    perm = list(permutation)
    for i in range(len(perm)):
        for j in range(i + 1, len(perm)):
            if perm[i] > perm[j]:
                count += 1
    return (-1) ** count
A = np.array([
    [2, 1, 3],
    [1, 0, 2],
    [4, 1, 1]
])
print("Ma trận A:")
print(A)
for p in Sn:
    sign = sgn(p)
    product = 1
    for i in range(n):
        product *= A[i][p[i] - 1]
    det += sign * product
print("Giá trị định thức của ma trận A là:", det)
print("Định thức tính bằng numpy:", round(np.linalg.det(A)))

Tập hoán vị Sn:
[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
Ma trận A:
[[2 1 3]
 [1 0 2]
 [4 1 1]]
Giá trị định thức của ma trận A là: 6
Định thức tính bằng numpy: 6


In [ ]:
# Đoạn code 1
def sgn_by_def(permutation):
    count = 0
    perm = list(permutation)
    for i in range(len(perm)):
        for j in range(i + 1, len(perm)):
            if perm[i] > perm[j]:
                count += 1
    return (-1) ** count
def phatsinh_dinhthuc(n):
  X = []
  for i in range(1,n+1):
      X.append(i)
  Sn = list(permutations(X))
  dinhthuc = ""
  for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = ""
        for i in range(1,n+1):
                sigma[sn.index(i)] = i
                product = product + "a"+ str(i)+str(sn.index(i)+1)
        dau = sgn_by_def(sigma)
        if dau != 1:
          product = "-" + product
        else:
          product = "+" + product
        dinhthuc = dinhthuc + product
        return  dinhthuc

print("Định thức dạng ký hiệu với n=2:")
print(phatsinh_dinhthuc(2))

print("Định thức dạng ký hiệu với n=3:")
print(phatsinh_dinhthuc(3))


Định thức dạng ký hiệu với n=2:
+a11a22
Định thức dạng ký hiệu với n=3:
+a11a22a33


In [ ]:
# Đoạn code 2
def tinhtoan_dinhthuc(A) :
    X=[]
    import math  #<-- bổ sung để sử dụng sqrt
    n = int (math.sqrt (A.size) )#<-- với ma trận vuống, kích thước là căn sở
    for i in range (1, n+1) :
              X.append (1)
    Sn = list(permutations (X) )
    dinhthuc = 0
    # ban đầu giá trị định thức là 0
    for sn in Sn:
        sigma = np.array([1])
        sigma. resize ([n])
        product = 1     # đặt giá trị cho tích ban đầu là 1
        for i in range (1,n+1) :
                sigma [sn. index (i)] = i
                product = product * A[i-1] [sn. index (i)] # luu ý chi sô #print (A[1-1] (sn. index (i)])
        dau = sgn_by_def (sigma)
        if dau != 1:
            product = product * (-1)
        # không xét trường hợp dẫu =1
        #khi dầu - -1 thì nhân với -1
        dinhthuc = dinhthuc + product
        return dinhthuc

In [1]:
# Hệ hai phương trình tuyến tính bậc 1:
import numpy as np
from scipy import linalg

A = np.array([[4, -2], [3, -5]])
A1 = np.array([[10, -2], [11, -5]])
A2 = np.array([[4, 10], [3, 11]])

def tinhtoan_dinhthuc(A, A1, A2):
    detA = linalg.det(A)
    detA1 = linalg.det(A1)
    detA2 = linalg.det(A2)
    return detA, detA1, detA2

detA, detA1, detA2 = tinhtoan_dinhthuc(A, A1, A2)
print("detA =", detA)
print("detA1 =", detA1)
print("detA2 =", detA2)

if detA != 0:
    x1 = detA1 / detA
    x2 = detA2 / detA
    print("Hai nghiệm của phương trình là: ", x1, x2)
else:
    print("Hệ phương trình vô nghiệm hoặc vô số nghiệm.")


detA = -14.0
detA1 = -28.0
detA2 = 14.000000000000004
Hai nghiệm của phương trình là:  2.0 -1.0000000000000002


In [2]:
# Ứng dụng 1
import numpy as np
points = np.array([
    [1181128.25, 603263.70],
    [1181136.18, 603266.68],
    [1181130.97, 603279.69],
    [1181125.77, 603281.91],
    [1181122.06, 603280.42]
])

def tinh_dientich_da_giac(points):
    n = len(points)
    S = 0
    for i in range(n):
        x_i, y_i = points[i]
        x_next, y_next = points[(i + 1) % n]
        S += (x_i * y_next) - (x_next * y_i)
    return abs(S) / 2

dientich = tinh_dientich_da_giac(points)
print("Diện tích đa giác là:", dientich, "m²")


Diện tích đa giác là: 139.56793212890625 m²


In [3]:
# Ứng dụng 2
from sympy import Matrix

M = Matrix([
    [0, 4, 1, 1],
    [4, 0, 0, 1],
    [3, 5, 2, 1],
    [2, 2, 5, 1]
])

detM = M.det()
V = abs(1/6 * detM)

print("Định thức của ma trận là:", detM)
print("Thể tích của tứ diện là:", V)


Định thức của ma trận là: -72
Thể tích của tứ diện là: 12.0000000000000


In [4]:
# Ứng dụng 3
from sympy import Matrix

M = Matrix([
    [0, 4, 1, 1],
    [4, 0, 0, 1],
    [3, 5, 2, 1],
    [2, 2, 5, 1]
])

det = M.det()
print(f"Định thức của ma trận: {det}")
if det == 0:
    print("Bốn điểm nằm trên cùng một mặt phẳng.")
else:
    print("Bốn điểm không nằm trên cùng một mặt phẳng.")


Định thức của ma trận: -72
Bốn điểm không nằm trên cùng một mặt phẳng.


In [5]:
# Ứng dụng 4
from sympy import symbols, Matrix

x, y, z = symbols('x y z')
MP = Matrix([
    [x, y, z, 1],
    [-1, 3, 2, 1],
    [0, 1, 0, 1],
    [-2, 0, 1, 1]
])

plane_eq = MP.det()
print(f"Phương trình mặt phẳng: {plane_eq} = 0")


Phương trình mặt phẳng: -4*x + 3*y - 5*z - 3 = 0


In [6]:
# Bài toán ứng dụng 3: Tính quỹ đạo của hành tinh/vệ tinh
from sympy import Matrix, symbols

x1, y1 = symbols('x1 y1')
x2, y2 = symbols('x2 y2')
x3, y3 = symbols('x3 y3')
x4, y4 = symbols('x4 y4')
x5, y5 = symbols('x5 y5')

M = Matrix([
    [x1**2, x1*y1, y1**2, x1, y1, 1],
    [x2**2, x2*y2, y2**2, x2, y2, 1],
    [x3**2, x3*y3, y3**2, x3, y3, 1],
    [x4**2, x4*y4, y4**2, x4, y4, 1],
    [x5**2, x5*y5, y5**2, x5, y5, 1],
])

print("Ma trận cho hệ phương trình:")
print(M)
M_numeric = Matrix([
    [1**2, 1*2, 2**2, 1, 2, 1],
    [2**2, 2*3, 3**2, 2, 3, 1],
    [3**2, 3*1, 1**2, 3, 1, 1],
    [4**2, 4*5, 5**2, 4, 5, 1],
    [5**2, 5*4, 4**2, 5, 4, 1],
])

print("\nMa trận số:")
print(M_numeric)
det = M_numeric.det()
print(f"\nĐịnh thức của ma trận: {det}")


Ma trận cho hệ phương trình:
Matrix([[x1**2, x1*y1, y1**2, x1, y1, 1], [x2**2, x2*y2, y2**2, x2, y2, 1], [x3**2, x3*y3, y3**2, x3, y3, 1], [x4**2, x4*y4, y4**2, x4, y4, 1], [x5**2, x5*y5, y5**2, x5, y5, 1]])

Ma trận số:
Matrix([[1, 2, 4, 1, 2, 1], [4, 6, 9, 2, 3, 1], [9, 3, 1, 3, 1, 1], [16, 20, 25, 4, 5, 1], [25, 20, 16, 5, 4, 1]])


NonSquareMatrixError: 

BÀI TẬP VỀ NHÀ


In [7]:
# Bài 1
from sympy import Matrix
A = Matrix([
    [1, 2, 3],
    [0, 4, 5],
    [7, 8, 9]
])

print("Ma trận A:")
print(A)

cofactor_matrix = A.cofactor_matrix()
print("\nMa trận hệ số kép (Cofactor matrix):")
print(cofactor_matrix)

adjoint_matrix = A.adjugate()
print("\nMa trận liên hợp (Adjoint matrix):")
print(adjoint_matrix)


Ma trận A:
Matrix([[1, 2, 3], [0, 4, 5], [7, 8, 9]])

Ma trận hệ số kép (Cofactor matrix):
Matrix([[-4, 35, -28], [6, -12, 6], [-2, -5, 4]])

Ma trận liên hợp (Adjoint matrix):
Matrix([[-4, 6, -2], [35, -12, -5], [-28, 6, 4]])


In [8]:
# Bài 2
from sympy import symbols, Matrix, Eq, solve

A, B, C, D = symbols('A B C D')
x1, y1 = 1, 2
x2, y2 = 3, 4
x3, y3 = 5, 1

eq1 = Eq(A*(x1**2 + y1**2) + B*x1 + C*y1 + D, 0)
eq2 = Eq(A*(x2**2 + y2**2) + B*x2 + C*y2 + D, 0)
eq3 = Eq(A*(x3**2 + y3**2) + B*x3 + C*y3 + D, 0)
solution = solve([eq1, eq2, eq3], (A, B, C, D))

print("Kết quả phương trình đường tròn:")
print(solution)


Kết quả phương trình đường tròn:
{A: 5*D/44, B: -31*D/44, C: -19*D/44}
