In [1]:
# Bài 1.1
import numpy as np

D = np.array([[1, 2], [3, 4]])
try:
    np.copyto(E, D)
except NameError as e:
    print(f"Lỗi: {e}")
except Exception as e:
    print(f"Lỗi khác: {e}")

E = np.array([[1, 2], [3, 5]])

np.copyto(E, D)

print("Mảng E sau khi copyto(E, D):")
print(E)


Lỗi: name 'E' is not defined
Mảng E sau khi copyto(E, D):
[[1 2]
 [3 4]]


In [2]:
#  Bài 1.2
import numpy as np

# Sử dụng numpy.matrix
try:
    x = np.array([['a','b'],['c','d']])
    y = 'x'
    C = np.matrix([[x, y], [1, 2]], dtype=object)
    print("Kết quả của print(C):")
    print(C)
except Exception as e:
    print(f"Đã xảy ra lỗi: {e}")

print("\n" + "="*30 + "\n")

# Lỗi với numpy.matrix nhiều hơn 2 chiều
try:
    A_error = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])
    print(A_error)
except ValueError as e:
    print("Ghi nhận lỗi khi tạo matrix 3 chiều:")
    print(f"Lỗi: {e}")

print("\n" + "="*30 + "\n")

# Sử dụng numpy.array cho mảng nhiều chiều
A_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Kết quả của print(A) khi A là một array 3 chiều:")
print(A_array)
print(f"\nSố chiều của mảng A: {A_array.ndim}")

Kết quả của print(C):
[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


Ghi nhận lỗi khi tạo matrix 3 chiều:
Lỗi: matrix must be 2-dimensional


Kết quả của print(A) khi A là một array 3 chiều:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Số chiều của mảng A: 3


In [3]:
# Bài 1.3
from numpy import matlib

# Tạo ma trận đơn vị G
G = matlib.identity(5)
print(G)

print("\n" + "="*30 + "\n")

# Tạo ma trận ngẫu nhiên H
print("--- Ma trận ngẫu nhiên H (3x2) ---")
print("(Lưu ý: Kết quả sẽ khác nhau mỗi lần chạy)")
H = matlib.randn(3,2)
print(H)

print("\n" + "="*30 + "\n")

# Tạo ma trận zero K
print("--- Ma trận zero K (4x4) ---")
K = matlib.zeros([4,4])
print(K)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


--- Ma trận ngẫu nhiên H (3x2) ---
(Lưu ý: Kết quả sẽ khác nhau mỗi lần chạy)
[[ 0.52687554  2.15390057]
 [ 0.53524182 -1.30254439]
 [ 0.20605558  1.76027714]]


--- Ma trận zero K (4x4) ---
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# Bài 2.2
import numpy as np

c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
M = np.mat([[1, 0], [0, 1]])
for i in range(len(c)):
    ci = np.mat([[c[i], 1], [1, 0]])
    M = M.dot(ci)

print("Ma trận kết quả:")
print(M)

pi_approx = M[0, 0] / M[1, 0]
print("Giá trị Pi gần đúng:", pi_approx)


AttributeError: module 'numpy' has no attribute 'math'

In [6]:
# Bài 3.2
import numpy as np
X = np.array([
    [1, 1],
    [1, 2],
    [1, 3],
    [1, 4],
    [1, 5]
])

Y = np.array([
    [1],
    [2],
    [4],
    [4],
    [6]
])


XT = X.T
A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)
A = A1.dot(A2)

print("Hệ số đường thẳng gần đúng nhất:")
print(f"Y = {A[0,0]:.4f} + {A[1,0]:.4f} * X")
Y_pred = X.dot(A)

errors = (Y - Y_pred)**2
sum_error = np.sum(errors)

print(f"Sai số tổng bình phương: {sum_error:.4f}")


Hệ số đường thẳng gần đúng nhất:
Y = -0.2000 + 1.2000 * X
Sai số tổng bình phương: 0.8000


Bài Tập Về nhà


In [7]:
# Bài 1
import numpy as np

def bpcuctieu(a):
    b = []
    o1 = []
    for i in range(len(a)):
        o1.append(1.0)
        b.append(i * 1.0)
    x = np.array([o1, b])
    u = np.dot(x, x.T)
    u_1 = np.linalg.inv(u)
    v = np.dot(u_1, x)
    y = np.array(a)
    A = np.dot(v, y)
    return A
dulieu = [10.0, 8, 7, 5, 2]

A = bpcuctieu(dulieu)
print(f"Phương trình tuyến tính gần đúng nhất: Y = {A[0]:.4f} + {A[1]:.4f} * X")

X_test = np.array([1.0, 0.0])
Y0 = np.dot(A, X_test)
X_test = np.array([1.0, 4.0])
Y4 = np.dot(A, X_test)

print(f"Dự đoán tại X=0: {Y0:.2f}")
print(f"Dự đoán tại X=4: {Y4:.2f}")


Phương trình tuyến tính gần đúng nhất: Y = 10.2000 + -1.9000 * X
Dự đoán tại X=0: 10.20
Dự đoán tại X=4: 2.60
