In [2]:
# Câu 1
import numpy as np
from numpy.linalg import norm
from math import acos, degrees
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
C = np.array([
    [1, 2, -1],
    [0, 3, 4],
    [2, -1, 0]
])

# a) Tính tổng A + B và tích số 3A - 2B
tong = A + B
tich_so = 3 * A - 2 * B

print("a) A + B =", tong)
print("   3A - 2B =", tich_so)

# b) Tính tích vô hướng A . B và góc giữa 2 vector
dot_product = np.dot(A, B)
cos_theta = dot_product / (norm(A) * norm(B))
angle_deg = round(degrees(acos(cos_theta)), 3)

print("\nb) A · B =", dot_product)
print("   Góc giữa A và B (độ):", angle_deg)

# c) Tính tích ma trận C^T * C
Ct = C.T
CtC = np.dot(Ct, C)

print("\nc) C^T * C =")
print(CtC)


a) A + B = [3 3 1 5]
   3A - 2B = [  4 -11  13 -10]

b) A · B = -8
   Góc giữa A và B (độ): 108.376

c) C^T * C =
[[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


In [3]:
# Câu 2
import numpy as np
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

# a) Tính tích ma trận M x N
tich_MN = np.dot(M, N)
print("a) M x N =")
print(tich_MN)

# b) Tính định thức của M (nếu có thể)
try:
    det_M = np.linalg.det(M)
    print("\nb) Định thức của M =", round(det_M, 3))
except np.linalg.LinAlgError:
    print("\nb) Không thể tính định thức vì M không phải ma trận vuông")

# c) Tính hạng của ma trận N
rank_N = np.linalg.matrix_rank(N)
print("\nc) Hạng của ma trận N =", rank_N)


a) M x N =
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]

b) Định thức của M = 0.0

c) Hạng của ma trận N = 2


In [4]:
# Câu 3
import numpy as np
P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])

B = np.array([4, 7, 9, 5])

# a) Tìm ma trận nghịch đảo của P
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P là:")
    print(np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch vì định thức bằng 0.")

# b) Giải hệ phương trình bằng cách dùng ma trận nghịch đảo
try:
    X = np.dot(P_inv, B)
    print("\nb) Nghiệm của hệ phương trình là (x, y, z, w):")
    print(np.round(X, 3))
except:
    print("Không thể giải hệ phương trình vì P không khả nghịch.")

# c) Kiểm tra nghiệm bằng cách nhân P với X và so sánh với B
try:
    check_B = np.dot(P, X)
    print("\nc) Kiểm tra lại P.X:")
    print(np.round(check_B, 3))
    print("So với vector B:")
    print(B)
except:
    print("Không thể kiểm tra vì không có nghiệm.")


a) Ma trận nghịch đảo của P là:
[[ 0.488 -0.093  0.023 -0.209]
 [ 0.035  0.279 -0.07   0.128]
 [-0.116  0.07   0.233 -0.093]
 [-0.012 -0.093  0.023  0.291]]

b) Nghiệm của hệ phương trình là (x, y, z, w):
[0.465 2.105 1.651 0.965]

c) Kiểm tra lại P.X:
[4. 7. 9. 5.]
So với vector B:
[4 7 9 5]


In [5]:
#  Câu 4
import numpy as np
Q = np.array([
    [4, -1, 0],
    [1, 3, -2],
    [0, 1, 2]
])

# a) Tìm các giá trị riêng (eigenvalues)
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("a) Các giá trị riêng của Q:")
print(np.round(eigenvalues, 3))

# b) Tìm các vector riêng (eigenvectors)
print("\nb) Các vector riêng tương ứng:")
for i in range(len(eigenvalues)):
    print(f"Vector riêng ứng với giá trị riêng {round(eigenvalues[i], 3)}:")
    print(np.round(eigenvectors[:, i], 3))

# c) Chuẩn hóa các vector riêng (độ dài = 1)
print("\nc) Vector riêng sau khi chuẩn hóa (norm = 1):")
for i in range(eigenvectors.shape[1]):
    v = eigenvectors[:, i]
    v_normalized = v / np.linalg.norm(v)
    print(f"Vector {i+1} (chuẩn hóa):")
    print(np.round(v_normalized, 3))


a) Các giá trị riêng của Q:
[3.453+0.j    2.773+1.468j 2.773-1.468j]

b) Các vector riêng tương ứng:
Vector riêng ứng với giá trị riêng (3.453+0j):
[0.833+0.j 0.455+0.j 0.313+0.j]
Vector riêng ứng với giá trị riêng (2.773+1.468j):
[-0.262-0.314j -0.782+0.j    -0.22 +0.417j]
Vector riêng ứng với giá trị riêng (2.773-1.468j):
[-0.262+0.314j -0.782-0.j    -0.22 -0.417j]

c) Vector riêng sau khi chuẩn hóa (norm = 1):
Vector 1 (chuẩn hóa):
[0.833+0.j 0.455+0.j 0.313+0.j]
Vector 2 (chuẩn hóa):
[-0.262-0.314j -0.782+0.j    -0.22 +0.417j]
Vector 3 (chuẩn hóa):
[-0.262+0.314j -0.782+0.j    -0.22 -0.417j]


/tmp/ipython-input-5-2199062494.py:17: DeprecationWarning: The Python built-in `round` is deprecated for complex scalars, and will raise a `TypeError` in a future release. Use `np.round` or `scalar.round` instead.
  print(f"Vector riêng ứng với giá trị riêng {round(eigenvalues[i], 3)}:")


In [6]:
# Câu 5
import numpy as np
R = np.array([
    [1, -2, 3],
    [2, 0, 1],
    [-1, 1, 4]
])

b = np.array([10, 8, 7])

# a) Giải hệ phương trình Rx = b bằng np.linalg.solve()
try:
    x1 = np.linalg.solve(R, b)
    print("a) Nghiệm của hệ phương trình Rx = b là:")
    print(np.round(x1, 3))
except np.linalg.LinAlgError:
    print("a) Hệ phương trình không có nghiệm duy nhất (R không khả nghịch).")

# b) Kiểm tra khả nghịch, tính nghịch đảo và giải lại hệ
try:
    R_inv = np.linalg.inv(R)
    x2 = R_inv @ b
    print("\nb) Ma trận R khả nghịch. Ma trận nghịch đảo R⁻¹ là:")
    print(np.round(R_inv, 3))
    print("\nNghiệm khi dùng nghịch đảo là:")
    print(np.round(x2, 3))
    print("\nSo sánh 2 nghiệm (solve vs nghịch đảo):")
    print("Chênh lệch tuyệt đối:", np.round(np.abs(x1 - x2), 6))
except np.linalg.LinAlgError:
    print("\nb) R không khả nghịch, không thể tính nghịch đảo.")

# c) Tính chuẩn Frobenius của R
fro_norm = np.linalg.norm(R, ord='fro')
print("\nc) Chuẩn Frobenius của R =", round(fro_norm, 3))


a) Nghiệm của hệ phương trình Rx = b là:
[2.783 0.043 2.435]

b) Ma trận R khả nghịch. Ma trận nghịch đảo R⁻¹ là:
[[-0.043  0.478 -0.087]
 [-0.391  0.304  0.217]
 [ 0.087  0.043  0.174]]

Nghiệm khi dùng nghịch đảo là:
[2.783 0.043 2.435]

So sánh 2 nghiệm (solve vs nghịch đảo):
Chênh lệch tuyệt đối: [0. 0. 0.]

c) Chuẩn Frobenius của R = 6.083
