In [8]:
# Bài 1
import numpy as np
from numpy.linalg import norm
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([
    [2, -1, 3],
    [1, 4, -2],
    [0, 2, 5]
])

# a) Tính A + B và 2A + 3B
tong = A + B
tich_vo_huong = 2 * A + 3 * B
print("a) A + B =", tong)
print("   2A + 3B =", tich_vo_huong)

# b) Tích vô hướng và góc giữa 2 vector
dot_product = np.dot(A, B)
cos_theta = dot_product / (norm(A) * norm(B))
angle_rad = np.arccos(cos_theta)
angle_deg = np.degrees(angle_rad)
print("b) A . B =", dot_product)
print("   Góc giữa A và B (độ) =", round(angle_deg, 3))

# c) Tính tích C * C^T
CCT = np.dot(C, C.T)
print("c) C * C^T =\n", CCT)


a) A + B = [2 3 1 6]
   2A + 3B = [ 3 11  2 14]
b) A . B = -5
   Góc giữa A và B (độ) = 99.594
c) C * C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


In [7]:
# Bài 2
from numpy.linalg import det, matrix_rank
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])
N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

# a) Tính M x N
product = np.dot(M, N)
print("a) M x N =\n", product)

# b) Định thức ma trận M
det_M = det(M)
print("b) Định thức của M =", round(det_M, 3))
if det_M == 0:
    print("   => Ma trận M không khả nghịch")
else:
    print("   => Ma trận M khả nghịch")

# c) Tính hạng của N
rank_N = matrix_rank(N)
print("c) Hạng của ma trận N =", rank_N)


a) M x N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
b) Định thức của M = 409.0
   => Ma trận M khả nghịch
c) Hạng của ma trận N = 4


In [6]:
# Bài 3
from numpy.linalg import inv, solve
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
])
b = np.array([6, 8, 3, 7])

# a) Tìm ma trận nghịch đảo
try:
    P_inv = inv(P)
    print("a) Ma trận nghịch đảo của P:\n", P_inv)

    # b) Giải hệ phương trình
    x = solve(P, b)
    print("b) Nghiệm của hệ phương trình là:\n", x)

    # c) Kiểm tra lại
    check = np.dot(P, x)
    print("c) Kiểm tra P * x:\n", check)
    print("   Vector hằng số b:\n", b)

except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch")


a) Ma trận nghịch đảo của P:
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
b) Nghiệm của hệ phương trình là:
 [2.         1.71428571 0.42857143 0.85714286]
c) Kiểm tra P * x:
 [6. 8. 3. 7.]
   Vector hằng số b:
 [6 8 3 7]


In [5]:
# Bài 4
import numpy as np
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

# a) Tính giá trị riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("a) Giá trị riêng của Q:")
print(eigenvalues)

# b) Vector riêng tương ứng
print("\nb) Vector riêng tương ứng:")
for i, vec in enumerate(eigenvectors.T):
    print(f"Vector riêng {i+1}:\n", vec)

# c) Chuẩn hóa vector riêng (độ dài = 1)
print("\nc) Vector riêng sau khi chuẩn hóa:")
normalized_vectors = []
for i, vec in enumerate(eigenvectors.T):
    norm_vec = vec / np.linalg.norm(vec)
    normalized_vectors.append(norm_vec)
    print(f"Vector riêng {i+1} (chuẩn hóa):\n", norm_vec)


a) Giá trị riêng của Q:
[6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]

b) Vector riêng tương ứng:
Vector riêng 1:
 [ 0.74846013+0.j -0.18941773+0.j  0.63555359+0.j]
Vector riêng 2:
 [-0.37423006+0.34234215j  0.09470887+0.57433055j  0.63555359+0.j        ]
Vector riêng 3:
 [-0.37423006-0.34234215j  0.09470887-0.57433055j  0.63555359-0.j        ]

c) Vector riêng sau khi chuẩn hóa:
Vector riêng 1 (chuẩn hóa):
 [ 0.74846013+0.j -0.18941773+0.j  0.63555359+0.j]
Vector riêng 2 (chuẩn hóa):
 [-0.37423006+0.34234215j  0.09470887+0.57433055j  0.63555359+0.j        ]
Vector riêng 3 (chuẩn hóa):
 [-0.37423006-0.34234215j  0.09470887-0.57433055j  0.63555359-0.j        ]


In [9]:
# Bài 5
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])

# a) Giải hệ phương trình Rx = b
x = np.linalg.solve(R, b)
print("a) Nghiệm của hệ phương trình Rx = b là:\n", x)

# b) Kiểm tra khả nghịch và giải lại bằng nghịch đảo
try:
    R_inv = np.linalg.inv(R)
    x2 = np.dot(R_inv, b)
    print("\nb) Ma trận R khả nghịch.")
    print("   Nghiệm bằng R^-1 * b là:\n", x2)
    print("   Hai nghiệm có giống nhau không?", np.allclose(x, x2))
except np.linalg.LinAlgError:
    print("\nb) Ma trận R không khả nghịch.")

# c) Tính chuẩn Frobenius
fro_norm = np.linalg.norm(R, ord='fro')
print("\nc) Chuẩn Frobenius của R =", round(fro_norm, 3))


a) Nghiệm của hệ phương trình Rx = b là:
 [2.78823529 1.52941176 1.18823529]

b) Ma trận R khả nghịch.
   Nghiệm bằng R^-1 * b là:
 [2.78823529 1.52941176 1.18823529]
   Hai nghiệm có giống nhau không? True

c) Chuẩn Frobenius của R = 8.0
